name: New Build System

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 1. Free Up Disk Space
        run: |
          sudo swapoff -a
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/local/lib/android
          docker image prune -a -f
          df -h

      - name: 2. Checkout Device Tree
        uses: actions/checkout@v4

      - name: 3. Install Tools & Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 python3
          sudo ln -sf /usr/bin/python2 /usr/bin/python
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: 4. Initialize and Sync Minimal Manifest
        run: |
          mkdir -p ~/twrp_build
          cd ~/twrp_build
          git config --global user.name "ahmedrba15-cell"
          git config --global user.email "ahmed@example.com"
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1
          repo sync -c --no-tags --no-clone-bundle -j$(nproc)

      - name: 5. Prepare Device Tree
        run: |
          # التعديل على الملف في مسار الجيت هاب مباشرة
          cd $GITHUB_WORKSPACE/device/lenovo/tb7104
          sed -i 's/BOARD_RAMDISK_COMPRESSION := .*/BOARD_RAMDISK_COMPRESSION := lzma/' BoardConfig.mk
          sed -i 's/BOARD_RECOVERYIMAGE_PARTITION_SIZE := .*/BOARD_RECOVERYIMAGE_PARTITION_SIZE := 17301504/' BoardConfig.mk
          echo "TARGET_STRIP := strip" >> BoardConfig.mk
          
          # نقل الشجرة المظبوطة لمجلد البناء
          mkdir -p ~/twrp_build/device/lenovo
          cp -r $GITHUB_WORKSPACE/device/lenovo/tb7104 ~/twrp_build/device/lenovo/
          echo "Device tree prepared and copied successfully!"

      - name: 6. Build Recovery Image
        run: |
          cd ~/twrp_build
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch omni_tb7104-eng || lunch twrp_tb7104-eng
          make clean
          make recoveryimage -j$(nproc)

      - name: 7. Upload Recovery Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-TB7104-Recovery
          path: /home/runner/twrp_build/out/target/product/tb7104/recovery.img
          
